
FROM node:20.18.0-alpine
RUN mkdir -p /app
WORKDIR /app

COPY package*.json ./

RUN npm install

# Jenkins에서 복사된 .env 파일을 빌드 컨텍스트에 포함
COPY .env ./

COPY . .

RUN npm run build

EXPOSE 3000
ENV PORT 3000
CMD ["npm", "run", "start"]
