
FROM node:20.18.0-alpine
RUN mkdir -p /app
WORKDIR /app

COPY package*.json ./

ENV NODE_ENV=production

RUN npm install --omit=dev

COPY . .

RUN npm run build

EXPOSE 3000
ENV PORT 3000
CMD ["npm", "run", "start"]
