FROM node:20.18.0-alpine
RUN mkdir -p /app
WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build
RUN npm run build-storybook

EXPOSE 3000
EXPOSE 6006 

ENV PORT 3000
ENV STORYBOOK_PORT 6006

RUN npm install -g concurrently

CMD ["concurrently", "npm:start", "npm:storybook"]
